---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vntauras/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/rm $DEPLOYPATH/deploy_server.php
    - /bin/rm $DEPLOYPATH/sync_and_deploy.bat
    - /bin/rm $DEPLOYPATH/sync.bat
